---
logging:
    enabled: true
    level: DEBUG
    to_console: true
core:
    num_workers: 20
inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/hosts_vmm.yml"
        group_file: "inventory/groups.yml"
